Add a dev container to facilitate development
TGSAI/mdio-python pull request #277
Opened 2023-09-08 16:16 UTC by markspec

Add a dev container to facilitate development and provide a conistent python/poetry/nox environment for developers.

2023-11-02 14:39 UTC, tasansal requested changes

2023-11-02 14:39 UTC, tasansal commented on notebooks/ingestion_and_export.ipynb
did this file creep in by accident? looks like a debug nb.

2023-11-02 14:39 UTC, tasansal commented on .devcontainer/Dockerfile
can we clean up the dockerfile (commented cells etc)

2023-11-02 14:39 UTC, tasansal commented on .devcontainer/post-install.sh
can we clean up the commented out commands

2023-11-02 14:39 UTC, tasansal commented on docs/development_env.md
> +### known issues:
```suggestion
### Known Issues:
```

2023-11-02 14:52 UTC, markspec commented on notebooks/ingestion_and_export.ipynb
I intentionally included the notebook.  As there is no constructor in mdio, debugging the export is a long process.  This notebook walks through the process required to test the export:

- Create segy
- Convert segy to mdio
- Check mdio file
- export mdio to segy 

It also demos the use of some debugging tools that may be beneficial to future developers.

2023-11-02 15:22 UTC, markspec commented on docs/development_env.md
> +### known issues:
Fixed in latest commit.

2023-11-03 15:29 UTC, tasansal requested changes

2023-11-03 15:29 UTC, tasansal commented on notebooks/ingestion_and_export.ipynb
Let's go ahead and remove this for now; we need a better place to put it. The notebooks here are strictly for rendering in the user documentation in read the docs.

2023-11-03 15:30 UTC, tasansal commented on docs/development_env.md
> +### Known issues:
```suggestion
### Known Issues:
```

2023-11-03 15:35 UTC, tasansal commented on docs/development_env.md
> +- `git config --global --add safe.directory \`pwd\` ` might be needed inside the container.
```suggestion
- `git config --global --add safe.directory $(pwd)` might be needed inside the container.
```
This fixes incorrect Markdown rendering

2023-11-03 15:37 UTC, tasansal commented on CONTRIBUTING.md
> +## How to install and run MDIO
```suggestion
## How to Install and Run MDIO
```

2023-11-03 15:42 UTC, markspec commented on notebooks/ingestion_and_export.ipynb
Removed

2023-11-03 15:56 UTC, tasansal approved these changes

2023-11-03 20:30 UTC, merged