AutoShopWrap grid override
TGSAI/mdio-python pull request #338
Opened 2024-01-12 16:42 UTC by markspec

This allows ingestion with gun indexed by unwrapping shot_point for shot_lines.

2024-02-08 17:22 UTC, tasansal commented
Hi @markspec, can we add at least 1 test for each configuration?

2024-02-08 17:24 UTC, tasansal commented
Closes https://github.com/TGSAI/mdio-python/issues/336

2024-03-06 21:40 UTC, tasansal requested changes

2024-03-06 21:40 UTC, tasansal commented on src/mdio/converters/segy.py
> +        "shot_line", "gun", "shot_point", "cable", "channel". For improved
Question here. Doesn't having `shot_point` cause an extremely sparse grid here? Doesn't this cause us to have every single `shot_point` in the grid for every `shot_line` and `gun` configuration? 

Haven't read the rest of the code yet, so maybe it will be answered later.

2024-03-06 21:40 UTC, tasansal commented on src/mdio/segy/geometry.py
> +class ShotGunGeometryType(Enum):
Can we elaborate on the configurations more, it's unclear.

2024-03-06 21:40 UTC, tasansal commented on poetry.lock
can we drop the lock file from your PR, its causing conflicts with main

2024-03-07 01:57 UTC, markspec commented on poetry.lock
Done

2024-03-07 01:57 UTC, markspec commented on src/mdio/segy/geometry.py
> +class ShotGunGeometryType(Enum):
Added description.

2024-03-07 15:33 UTC, tasansal requested changes

2024-03-07 15:33 UTC, tasansal commented on src/mdio/converters/segy.py
> +        "shot_line", "gun", "shot_point", "cable", "channel". For improved
@markspec ?

2024-03-07 15:33 UTC, tasansal commented on tests/integration/conftest.py
> +    guns: list = None,
```suggestion
    guns: list | None = None,
```

2024-03-07 15:33 UTC, tasansal commented on .devcontainer/Dockerfile
>  ARG POETRY_VERSION="1.6.1"
```suggestion
ARG POETRY_VERSION="1.8.2"
```

2024-03-07 15:33 UTC, tasansal commented on src/mdio/segy/geometry.py
> +                )
```suggestion
                msg = (
                    f"Shot line {shot_line} has {num_shots_sl} when using div by "
                    f"{num_guns_sl} (num_guns) has  {np.unique(mod_shots)} unique mod shots."
                )
                logger.info(msg)
```

2024-03-07 15:33 UTC, tasansal commented on tests/integration/conftest.py
> +        guns = [
this case is showing not covered in coverage report. If this test case is invalid, we can remove this, or if its missing it we should add it.

2024-03-08 21:03 UTC, tasansal commented on src/mdio/converters/segy.py
> +        "shot_line", "gun", "shot_point", "cable", "channel". For improved
per @markspec the grid stays dense; resolved.

2024-03-08 21:03 UTC, tasansal approved these changes

2024-03-08 21:04 UTC, tasansal commented
@markspec approved but there's a test conflict; please fix so we can merge. thanks!

2024-03-10 18:49 UTC, merged